language: python
os:
  - linux
  # - windows # currently not supported by travis..., add another time again
  # - osx # currently not supported by travis..., add another time again
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  # - "3.10" # seems not yet available at travis
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov

# command to run tests
script:
  - pytest --cov=polyloxpgen

# this automatically reports to codecov,
# which create their README badge
after_success:
  - codecov
